/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alufn_checker_6 (
    input [5:0] alufn,
    output reg invalid
  );
  
  
  
  always @* begin
    
    case (alufn)
      6'h00: begin
        invalid = 1'h0;
      end
      6'h01: begin
        invalid = 1'h0;
      end
      6'h18: begin
        invalid = 1'h0;
      end
      6'h1e: begin
        invalid = 1'h0;
      end
      6'h16: begin
        invalid = 1'h0;
      end
      6'h1a: begin
        invalid = 1'h0;
      end
      6'h20: begin
        invalid = 1'h0;
      end
      6'h21: begin
        invalid = 1'h0;
      end
      6'h23: begin
        invalid = 1'h0;
      end
      6'h33: begin
        invalid = 1'h0;
      end
      6'h35: begin
        invalid = 1'h0;
      end
      6'h37: begin
        invalid = 1'h0;
      end
      6'h02: begin
        invalid = 1'h0;
      end
      default: begin
        invalid = 1'h1;
      end
    endcase
  end
endmodule
