/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module find_zvn_9 (
    input [15:0] s,
    input x15,
    input y15,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [1-1:0] M_findn_n;
  reg [1-1:0] M_findn_s15;
  find_n_15 findn (
    .s15(M_findn_s15),
    .n(M_findn_n)
  );
  
  wire [1-1:0] M_findz_z;
  reg [16-1:0] M_findz_s;
  find_z_16 findz (
    .s(M_findz_s),
    .z(M_findz_z)
  );
  
  wire [1-1:0] M_findv_v;
  reg [1-1:0] M_findv_x15;
  reg [1-1:0] M_findv_y15;
  reg [1-1:0] M_findv_s15;
  find_v_17 findv (
    .x15(M_findv_x15),
    .y15(M_findv_y15),
    .s15(M_findv_s15),
    .v(M_findv_v)
  );
  
  always @* begin
    M_findn_s15 = s[15+0-:1];
    n = M_findn_n;
    M_findv_x15 = x15;
    M_findv_y15 = y15;
    M_findv_s15 = s[15+0-:1];
    v = M_findv_v;
    M_findz_s = s[0+15-:16];
    z = M_findz_z;
  end
endmodule
