/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module find_n_24 (
    input s15,
    output reg n
  );
  
  
  
  always @* begin
    n = s15;
  end
endmodule
