/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mux4_25 (
    input s1,
    input s0,
    input choice0,
    input choice1,
    input choice2,
    input choice3,
    output reg o
  );
  
  
  
  always @* begin
    
    case ({s0, s1})
      2'h0: begin
        o = choice0;
      end
      2'h2: begin
        o = choice1;
      end
      2'h1: begin
        o = choice2;
      end
      2'h3: begin
        o = choice3;
      end
      default: begin
        o = choice0;
      end
    endcase
  end
endmodule
