/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boole16_12 (
    input [15:0] x,
    input [15:0] y,
    input [3:0] alufn,
    output reg [15:0] o
  );
  
  
  
  wire [(5'h10+0)-1:0] M_mux_o;
  reg [(5'h10+0)-1:0] M_mux_s1;
  reg [(5'h10+0)-1:0] M_mux_s0;
  reg [(5'h10+0)-1:0] M_mux_choice0;
  reg [(5'h10+0)-1:0] M_mux_choice1;
  reg [(5'h10+0)-1:0] M_mux_choice2;
  reg [(5'h10+0)-1:0] M_mux_choice3;
  
  genvar GEN_mux0;
  generate
  for (GEN_mux0=0;GEN_mux0<5'h10;GEN_mux0=GEN_mux0+1) begin: mux_gen_0
    mux4_20 mux (
      .s1(M_mux_s1[GEN_mux0*(1)+(1)-1-:(1)]),
      .s0(M_mux_s0[GEN_mux0*(1)+(1)-1-:(1)]),
      .choice0(M_mux_choice0[GEN_mux0*(1)+(1)-1-:(1)]),
      .choice1(M_mux_choice1[GEN_mux0*(1)+(1)-1-:(1)]),
      .choice2(M_mux_choice2[GEN_mux0*(1)+(1)-1-:(1)]),
      .choice3(M_mux_choice3[GEN_mux0*(1)+(1)-1-:(1)]),
      .o(M_mux_o[GEN_mux0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  always @* begin
    M_mux_s1[0+15-:16] = y[0+15-:16];
    M_mux_s0[0+15-:16] = x[0+15-:16];
    M_mux_choice0[0+15-:16] = alufn[0+0-:1];
    M_mux_choice1[0+15-:16] = alufn[1+0-:1];
    M_mux_choice2[0+15-:16] = alufn[2+0-:1];
    M_mux_choice3[0+15-:16] = alufn[3+0-:1];
    o[0+15-:16] = M_mux_o[0+15-:16];
  end
endmodule
