/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare16_18 (
    input alufn2,
    input alufn1,
    input z,
    input v,
    input n,
    output reg cmp0
  );
  
  
  
  always @* begin
    
    case ({alufn2, alufn1})
      2'h1: begin
        cmp0 = z;
      end
      2'h2: begin
        cmp0 = (n ^ v);
      end
      2'h3: begin
        cmp0 = z | (n ^ v);
      end
      default: begin
        cmp0 = 1'h0;
      end
    endcase
  end
endmodule
