/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module find_z_25 (
    input [15:0] s,
    output reg z
  );
  
  
  
  reg i;
  
  always @* begin
    i = s[15+0-:1] | s[14+0-:1] | s[13+0-:1] | s[12+0-:1] | s[11+0-:1] | s[10+0-:1] | s[9+0-:1] | s[8+0-:1] | s[7+0-:1] | s[6+0-:1] | s[5+0-:1] | s[4+0-:1] | s[3+0-:1] | s[2+0-:1] | s[1+0-:1] | s[0+0-:1];
    z = !i;
  end
endmodule
