/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module find_zvn_21 (
    input [15:0] s,
    input x15,
    input y15,
    input alufn0,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  always @* begin
    z = (~|s);
    v = (x15 & (y15 ^ alufn0) & !s[15+0-:1]) | (!x15 & !(y15 ^ alufn0) & s[15+0-:1]);
    n = s[15+0-:1];
  end
endmodule
